project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /extension/src/_locales/en/messages.json
    translation: /extension/src/_locales/%two_letters_code%/messages.json
    type: chrome
