project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

pull_request_title: Translation updates from Crowdin
pull_request_labels: [ crowdin ]

files:
  - source: /extension/src/_locales/en/messages.json
    translation: /extension/src/_locales/%two_letters_code%/messages.json
    skip_untranslated_strings: true
    skip_untranslated_files: true
    type: chrome
