[package]
name = "firefoxpwa-background"
version = "0.0.0"
edition = "2021"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
tauri-winrt-notification = { version = "0.1.2", default-features = false }
trayicon = { git = "https://github.com/fkrull/trayicon-rs", rev = "4e9f223", default-features = false }
winit = { version = "0.28.7", default-features = false }
