[package]
name = "firefoxpwa-background"
version = "0.0.0"
edition = "2021"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
tauri-winrt-notification = { git = "https://github.com/tauri-apps/winrt-notification", rev = "1ebf2f4", default-features = false }
trayicon = { git = "https://github.com/fkrull/trayicon-rs", rev = "4e9f223", default-features = false }
winit = { git = "https://github.com/rust-windowing/winit", rev = "5e77d70", default-features = false }
