# This is a recipe file for cargo-make <https://github.com/sagiegurari/cargo-make> used to manage the project

[config]
skip_core_tasks = true

### BUILDERS ###

[tasks.build]
description = "Build the project"
command = "cargo"
args = ["build", "--release"]

### INSTALLERS ###

[tasks.install.windows]
dependencies = ["build"]
install_script = [
    "heat >nul 2>nul || echo FATAL: Make sure the WiX Toolset is installed and available in the PATH environment variable && exit 1",
    "cargo-wix help >nul 2>nul || cargo install cargo-wix --git https://github.com/volks73/cargo-wix.git --rev cc582226702a793fc9e1c20cdf99399663d6a2df",
]
script = [
    "heat dir userchrome -o packages/wix/userchrome.wxs -scom -srd -sreg -gg -cg UserChrome -dr UserChromeDir -var wix.UserChromeSource",
    "cargo wix --verbose --no-build --nocapture --install"
]

[tasks.install.linux]
dependencies = ["build"]
script = """
# Use sudo if it exists
SUDO=$(which sudo) || $(echo "")

# Copy all files to the correct locations
$SUDO install -D target/release/firefoxpwa /usr/bin/firefoxpwa
$SUDO install -D target/release/firefoxpwa-connector /usr/libexec/firefoxpwa-connector
$SUDO install -D manifests/linux.json /usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json
$SUDO install -D manifests/linux.json /usr/lib64/mozilla/native-messaging-hosts/firefoxpwa.json

# Copy the userchrome directory to the correct location
$SUDO mkdir -p /usr/share/firefoxpwa/userchrome/
$SUDO cp -R userchrome/* /usr/share/firefoxpwa/userchrome/
"""

[tasks.install.mac]
dependencies = ["build"]
script = """
# Use sudo if it exists
SUDO=$(which sudo) || $(echo "")

# Install Command Line Tools for Xcode
$SUDO xcode-select --install || true

# Copy all files to the correct locations
$SUDO install -d /usr/local/bin
$SUDO install -v target/release/firefoxpwa /usr/local/bin/firefoxpwa

$SUDO install -d /usr/local/libexec
$SUDO install -v target/release/firefoxpwa-connector /usr/local/libexec/firefoxpwa-connector

$SUDO install -d /Library/Application\\ Support/Mozilla/NativeMessagingHosts
$SUDO install -v manifests/macos.json /Library/Application\\ Support/Mozilla/NativeMessagingHosts/firefoxpwa.json

# Copy the userchrome directory to the correct location
$SUDO mkdir -p /usr/local/share/firefoxpwa/userchrome/
$SUDO cp -R userchrome/* /usr/local/share/firefoxpwa/userchrome/
"""

[tasks.install]
description = "Install the project"
script = [
    "echo FATAL: This environment does not support automatic installation using cargo-make",
    "exit 1"
]

### OTHERS ###

[tasks.set-version]
description = "Set version to given version or current git tag"
script_runner="@duckscript"
script = """
if ${1}
    # Use first argument
    pwa_ver = set ${1}
else
    # No argument, find tag from git
    git_tag = exec git describe --tags --abbrev=0
    assert_eq ${git_tag.code} 0 "No version provided to task and unable to retrieve git tag"
    pwa_ver = trim ${git_tag.stdout}
    release git_tag
    unset git_tag
end
# Remove single leading v if it exists
if starts_with ${pwa_ver} "v"
    pwa_ver = substring ${pwa_ver} 1
end
cargo_toml_path = set "./Cargo.toml"
chrome_jsm_path = set "./userchrome/profile/chrome/pwa/chrome.jsm"
cargo_toml_exists = is_file ${cargo_toml_path}
chrome_jsm_exists = is_file ${chrome_jsm_path}
if ${cargo_toml_exists} and ${chrome_jsm_exists}
    cargo_toml_replace = concat "version = \\"" ${pwa_ver} "\\""
    chrome_jsm_replace = concat "DISTRIBUTION_VERSION = '" ${pwa_ver} "'"
    cargo_toml = readfile ${cargo_toml_path}
    chrome_jsm = readfile ${chrome_jsm_path}
    echo "Replacing" ${cargo_toml_replace}
    cargo_toml = replace ${cargo_toml} "version = \\"0.0.0\\"" ${cargo_toml_replace}
    echo "Replacing" ${chrome_jsm_replace}
    chrome_jsm = replace ${chrome_jsm} "DISTRIBUTION_VERSION = '0.0.0'" ${chrome_jsm_replace}
    writefile ${cargo_toml_path} ${cargo_toml}
    writefile ${chrome_jsm_path} ${chrome_jsm}
else
    assert_fail "Unable to locate ./Cargo.toml and ./userchrome/profile/chrome/pwa/chrome.jsm"
end
"""
