group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"

newline_style = "Unix"

overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
